### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by MarkWieczorek** [alexellis/upload-assets#10]
The upload-assets action has worked great for me for the last couple releases I've put out (the last of which was 8 months ago). However, when putting out a release today, I received the error: "Resource not accessible by integration". 

I'm using this in conjunction with carlosperate/download-file-action@v2, and everything appears to be ok until the very end as shown in this workflow: https://github.com/SHTOOLS/SHTOOLS/actions/runs/7555899212/job/20571820692

<img width="688" alt="Screenshot 2024-01-17 at 14 08 45" src="https://github.com/alexellis/upload-assets/assets/8697285/dfebb48a-99c6-49c8-8a91-7a172d6bdb05">

Does anyone have any idea what the problem might be? As shown, the file is sucessully created, and the correct file path is passed to upload-asset. Here is the exact code in the action:

```
    - name: Download tarball archive
      uses: carlosperate/download-file-action@v2
      id: download-tarball
      with:
        file-url: 'https://github.com/SHTOOLS/SHTOOLS/archive/${{ env.RELEASE_VERSION }}.tar.gz'

    - name: Upload tarball as release asset
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["${{ steps.download-tarball.outputs.file-path }}"]'
```
