### ISSUE TITLE
Use tag name or release url as input

### ISSUE THREAD

**Issue by fraciril** [alexellis/upload-assets#4]
Hi! I've been using this Github Action and I run into an issue:

The release must use `${{ github.ref }}` as its tag:

https://github.com/alexellis/upload-assets/blob/f055c93bb9c5d934b26573f22c020a3b86bf7372/src/get-release.js#L11

This may not be a great idea, as seen here: https://github.com/actions/create-release/issues/116.

I think there should be an option to specify either the tag name or the release url, like https://github.com/actions/upload-release-asset does. This would both avoid the mentioned issue and let the users pick their desired release tags.
Thank you!

**Comment by alexellis** [comment]
Help me understand your workflow.

How do you tend to create your releases? I do it by creating a release in the GitHub UI.

**Comment by tillkruss** [comment]
I ran into this as well when using `workflow_dispatch`. Having the repository and tag name as optional inputs would be useful.

**Comment by psarras** [comment]
Hey, I want to add the assets using this action but on a specific release that I create on the fly.
@alexellis if it helps I am currently creating the release whenever a PR goes through to the release branch like so:

```
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-number-${{ env.BUILD_NUMBER }}
          release_name: ${{env.BUILD_NUMBER}} Release
          draft: false
          prerelease: false
```
I used to then do this using the deprecated now plugin

```
      - name: Upload Release Asset 1
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: something.3dm
          asset_name: something.3dm
          asset_content_type: application/zip
```
