### ISSUE TITLE
Unable to upload assets

### ISSUE THREAD

**Issue by Genysys** [alexellis/upload-assets#6]
I am trying to upload a binary with in git action using https://github.com/alexellis/upload-assets . Here is the snippet of where I call it. 

```yaml
      - name: Prepare executables for uploading
        run: |
          mkdir executables
          # mv target/production/node-template executables/node-template
          mv target/debug/foo executables/foo

      - name: Upload node template executables to assets
        uses: alexellis/upload-assets@0.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["executables/*"]'
```

Unfortunately , I get the error:

```bash
Run alexellis/upload-assets@0.3.0
Error: Not Found
```

I would appreciate any pointers on resolving this , as I can't understand why it can't find the binary

**Comment by vandot** [comment]
I am getting the same error `Error: Not Found`
Tried adding `contents: write` permission didn't helped, tried debugging it on the runner and this section of code works, it prints correct file
```
      if(assetPath.indexOf("*") > -1) {
        const files = glob.sync(assetPath,{ nodir: true })
        for (const file of files) {
            paths.push(file)
        }
      }
```
Tried debugging workflow with `ACTIONS_STEP_DEBUG: true` but no additional logs, this is [all](https://github.com/ethersphere/gateway-proxy/runs/6799937227?check_suite_focus=true#step:4:7)

Update:
So `Not Found` means release not found and not files 🤦

**Comment by nazar-pc** [comment]
Yes, it must be release or pre-release. Drafts and tags don't support uploading of files.

**Comment by vernak2539** [comment]
Hello! I'm running into this same problem. In my action, the second step is creating a release. I've confirmed that the tag and release are both created, so I'd think that the upload can happen. 

My workflow looks like this
```yml
name: Build and Publish
on: [push]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rymndhng/release-on-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: patch
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17.6'
      - run: make build_all
      - uses: actions/upload-artifact@v3
        with:
          name: package-darwin-arm46
          path: build/package-darwin-arm46
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          ACTIONS_STEP_DEBUG: true
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./build/package*"]'
```

I've tried with both `GITHUB_TOKEN: ${{ github.token }}` and `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}` to no avail. ~I tried to set up the debugging~ ~Checking this again, seems I did it wrong~ Checked, still no extra output. Output:

```
Run alexellis/upload-assets@0.2.2
  with:
    asset_paths: ["./build/package*"]
  env:
    GITHUB_TOKEN: ***
    ACTIONS_STEP_DEBUG: true
{ owner: 'vernak[2](https://github.com/vernak2539/repo/runs/7497825506?check_suite_focus=true#step:10:2)5[3](https://github.com/vernak2539/repo/runs/7497825506?check_suite_focus=true#step:10:3)9', repo: 'repo' } refs/heads/master
Error: Not Found
```

Any thoughts? (the repo is a private one, but the tokens should have access)
