### ISSUE TITLE
"Error: Not Found" when using the action

### ISSUE THREAD

**Issue by asgrim** [alexellis/upload-assets#7]
I made an isolated repo to test this, as I can't seem to get it working: 

https://github.com/asgrim/upload-assets-test

Using the action [like this](https://github.com/asgrim/upload-assets-test/blob/1.0.x/.github/workflows/upload-asset-test.yml#L27-L33):

```yaml
      - name: "Upload assets latest release"
        uses: alexellis/upload-assets@0.3.0 # also tried 0.2.2
        env:
          ACTIONS_STEP_DEBUG: true
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths:  '["test-*"]'
```

[The output](https://github.com/asgrim/upload-assets-test/runs/7520617432?check_suite_focus=true#step:3:8) is nothing more than:

```
Run alexellis/upload-assets@0.3.0
  with:
    asset_paths: ["test-*"]
  env:
    ACTIONS_STEP_DEBUG: true
    GITHUB_TOKEN: ***
Error: Not Found
```

There is definitely a release: https://github.com/asgrim/upload-assets-test/releases/tag/1.0.0

I tried adding the `permissions:` mentioned, as well as using 0.2.2 (as per README) as well as 0.3.0 (latest).
